annogram.js
https://github.com/dhowe/annograms/issues/1
=>  fix position of 'from...' line

annogram.js
refer to https://github.com/dhowe/annograms/issues/3
=> Avoid lb before punctuation

annogram.js
https://github.com/dhowe/annograms/issues/1
=> adjust source info display

annogram.js
=> fix to Issue#3

annogram.js
refer to https://github.com/dhowe/annograms/issues/12 
a cell can be added in Observablehq like this
```js
{
let targetDiv = html`<div></div>`
annogram.displayAnimated(poem, targetDiv);
return targetDiv;
}
```
=> Add animated cell

annogram.js
this should fix the `start` property in the lazy data
refer to https://github.com/dhowe/annograms/issues/15
=> fix to annoteLazy

annogram.js
refer to https://github.com/dhowe/annograms/issues/12
updated api:
```js
annogram.displayAnimated(poem, targetDiv, (optional) delayInMs, (optional) fadeInAnimationDurationInMs);
```
example
```js
{
let targetDiv = html`<div></div>`
annogram.displayAnimated(poem, targetDiv, 500);
return targetDiv;
}
```
=> Adjust animation styles

annogram.js, example.css
refer to https://github.com/dhowe/annograms/issues/21
new API:
```js
annogram.asLineAnimation(poem, options);
// options.width: number, the width of display div in px, default is 800
// options.height: number, the height of display div in px, default is 400
// options.delayMs: number, the delay of line appearing, in ms, default is 500
// options.fadeInMs: number, the length of the lines' fade in animation, in ms, default it 100
// options.paragraphIndent: number, default is 0, unit is per character
// options.warpIndent: number, default is 8, unit is per character
```
=> asLineAnimation

example.css
=> Adjust css for source window

annogram.js, test/annogram-tests.js
Fix this (the `start` attribute in `meta` for lines start with `<p>`)
=> Fix as html

annogram.js
=> change author name display

annogram.js, example.css
#29 
```js
annogram.asLineAnimation(poem, {autoScroll : true});
```
=> add options for autoscroll

annogram.js, example.css
=> Adjust animation

annogram.js
=> fix to default animation display

annogram.js
#30 
```js
annogram.asLineAnimation(poem,{cleanLB:true})
```
=> add option for cleanLB

example.css, index.html
=> Annotation toggle

annogram-html.js, annogram.js, example.css, index.html
=> change for text selection

data/The_Modern_Japanese_Prose_Poem_An_Anthology_of_Six_Poets_by_Dennis_Keene.json
fix to #35, json file of The Modern Japanese Prose Poem An Anthology of Six Poets by Dennis Keene, first two poets
=> Create new json file

text/The_Modern_Japanese_Prose_Poem_An_Anthology_of_Six_Poets_by_Dennis_Keene.txt
Fix to #35 , text of The Modern Japanese Prose Poem An Anthology of Six Poets by Dennis Keene, first two poets
=> Add new text

text/The_Modern_Japanese_Prose_Poem_An_Anthology_of_Six_Poets_by_Dennis_Keene.txt
Fix to #35, add the rest of the poems in the Modern Japanese Prose Poem.
=> Add the rest of the poems

data/The_Modern_Japanese_Prose_Poem_An_Anthology_of_Six_Poets_by_Dennis_Keene.json
Fix to #35, convert the rest of the poems to JSON format.
=> Update JSON file.

annogram-html.js, index.html, index_scroll.html
=> add scroll webpage
